### PR TITLE
Math magicians: full website

### PR DESCRIPTION
**Pull request by PrantoshB**
### Hello CR 👋
---

#### In this branch, I have:

- [x] Added Homepage and Quotes Page
- [x] Customized the look of the web app using CSS
- [x] Followed Git and GitHub flow
- [x] Fixed Linters Errors

[Click Here](https://prantoshb.github.io/Math-Magicians/) to view the Live Demo 🚀

#### Thanks 🍻
Prantosh

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @PrantoshB , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- All technical requirements met for this milestone.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly make sure you have added the section `Future Features`, which includes 1-3 potential features to be added. It is a part of the general requirements for every project you will be working on here at Microverse.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [x] I see you have used function declaration for defining your functions. However, since the introduction of arrow functions in ES6, it is a convention to use arrow functions where ever possible. I would strongly recommend using arrow functions throughout your code base.
- [x] Consider putting your navbar in its own component. Since react is all about splitting code into smaller reusable components, It would make much more sense if navbar had its own component.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PrantoshB** [comment]
Hello @muneebulrehman, Thanks for the suggestions.

But can you provide the source, where it's written that `Future Features` is a general requirement?
As me and any of my friends have never faced any issues for this reason. I have checked your repositories too. I can't find any section for the `Future Features`.
Please elaborate the issue.

Thanks

**Comment by muneebulrehman** [comment]
> Hello @muneebulrehman, Thanks for the suggestions.
> 
> But can you provide the source, where it's written that `Future Features` is a general requirement? As me and any of my friends have never faced any issues for this reason. I have checked your repositories too. I can't find any section for the `Future Features`. Please elaborate the issue.
> 
> Thanks

Sure @PrantoshB. ⬇️
image

Regarding the absence of the same from my repo, this README template is the new one, like 1 month old. That is why you won't find me using this template.

**Comment by PrantoshB** [comment]
> > Hello @muneebulrehman, Thanks for the suggestions.
> > But can you provide the source, where it's written that `Future Features` is a general requirement? As me and any of my friends have never faced any issues for this reason. I have checked your repositories too. I can't find any section for the `Future Features`. Please elaborate the issue.
> > Thanks
> 
> Sure @PrantoshB. ⬇️ image
> 
> Regarding the absence of the same from my repo, this README template is the new one, like 1 month old. That is why you won't find me using this template.

Thanks @muneebulrehman 🤝 for the detailed explanation. I'll refactor the PR as you have suggested.

**Comment by muneebulrehman** [comment]
> > > Hello @muneebulrehman, Thanks for the suggestions.
> > > But can you provide the source, where it's written that `Future Features` is a general requirement? As me and any of my friends have never faced any issues for this reason. I have checked your repositories too. I can't find any section for the `Future Features`. Please elaborate the issue.
> > > Thanks
> > 
> > 
> > Sure @PrantoshB. ⬇️ image
> > Regarding the absence of the same from my repo, this README template is the new one, like 1 month old. That is why you won't find me using this template.
> 
> Thanks @muneebulrehman 🤝 for the detailed explanation. I'll refactor the PR as you have suggested.

Happy to help @PrantoshB

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @PrantoshB, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All linters passing
- All requirements completed
- Professional readme

giphy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PrantoshB** [comment]
Thanks @sja-thedude 🥂
Have a great day 💐

**Pull request merged**
